version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
      - ./custom:/app/custom
    environment: 
      - PYTHONPATH=$PYTHONPATH:"/home/fay/project/RasaXDocker/custom"
    command:
      - run
  action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
    environment: 
      - PYTHONPATH=$PYTHONPATH:"/home/fay/project/RasaXDocker/actions"
  redis:
    image: redis:latest